### ISSUE TITLE
NAG compiler support

### ISSUE THREAD

**Issue by wadudmiah** [szaghi/FoBiS#103]
Hi, do you have any timeline on when NAG compiler support will be available?

Cheers,
Wadud.

**Comment by szaghi** [comment]
Dear Wadud,

probably the timeline is currently infinity... I have not access to NAG compiler (too costly), thus I cannot get the necessary information for support it. Indeed, it should be quite simple even without a direct access, but I need your help.

If you can provide me the information I need and you could do some tests, I think the support to NAG will be trivial to add.

Let me know if you can help me and I'll start the enhancement.

Cheers.

**Comment by wadudmiah** [comment]
Hi Stefano,

I can certainly help you, but there is also another option of obtaining a one month trial licence for the compiler (we can extend it to two months if required). Let me know what you would prefer. 

Regards,
Wadud.

**Comment by szaghi** [comment]
Hi Wadud,

great!

NAG is surely one of the best Fortran compiler, I would like to test it, but not now (I am very busy). For now, it could be more convenient (for me) to exploit your kind help. 

Tomorrow I should have the time to start to add NAG support. 

The information I need are simple and few:

+ name of the compiler executable;
+ I assume it uses the `-c` flag to compile without link, but if not, please tell me the correct switch;
+ flag to tell where *compiled module objects* (`.mod`) are placed, e.g. in GNU fortran it is `-J`, in Intel fortran it is `-module` for example;
+ name (if any) of the MPI version of the compiler, otherwise mpif90 is generally set;
+ flag (if any) to enable OpenMP directives, e.g. in GNU fortran it is `-fopenmp`;
+ flag (if any) to enbale CAF, e.g. in GNU fortran it is `-fcoarray`;
+ flags (compile and link, if any) to enebale coverage, e.g. in GNU fortran they are `[-ftest-coverage -fprofile-arcs, -fprofile-arcs]`;
+ flags (compile and link, if any) to enable profile, e.g. in GNU fortran they are `[-pg, -pg]`.

Once I have this info I can start to add the support.

**Comment by wadudmiah** [comment]
> name of the compiler executable;
`nagfor`
> I assume it uses the -c flag to compile without link, but if not, please tell me the correct switch;
that's correct
> flag to tell where compiled module objects (.mod) are placed, e.g. in GNU fortran it is -J, in Intel 
> fortran it is -module for example;
flag is `-mdir`
> name (if any) of the MPI version of the compiler, otherwise mpif90 is generally set;
It doesn't come with an MPI implementation but it works with OpenMPI. OpenMPI does have command `mpif90`
> flag (if any) to enable OpenMP directives, e.g. in GNU fortran it is -fopenmp;
flag is `-openmp`
> flag (if any) to enbale CAF, e.g. in GNU fortran it is -fcoarray;
flag is `-num_images=N` where N is the number of images. N is set to 1, i.e. no parallelism. It only recognises coarray syntax. 
> flags (compile and link, if any) to enebale coverage, e.g. in GNU fortran they are [-ftest-coverage 
> -fprofile-arcs, -fprofile-arcs];
NAG compiler does not have this feature.
> flags (compile and link, if any) to enable profile, e.g. in GNU fortran they are [-pg, -pg].
flag is `-pg`

Let me know if you need any further information.

**Comment by szaghi** [comment]
Hi @wadudmiah 

sorry for my delay, this is a busy "period" (one year and more...).

I just uploaded a branch for testing the support to NAG, just clone this 

https://github.com/szaghi/FoBiS/tree/feature/testing-nag

```sh
git clone https://github.com/szaghi/FoBiS
cd FoBiS
git checkout feature/testing-nag
```

after cloning you should be ready to go

```sh
cd /cloning_path/src/unittest/python/build-test1/src
/cloning_path/src/main/python/FoBiS.py build -compiler nag
```

Let me know your feedback when you have ones or want to share.

Cheers

**Comment by wadudmiah** [comment]
Hi Stefano,

No worries about the "delay"! I'm also going through a busy phase too :-) I will check this out in the next week and will give you some feedback. 

Cheers!

**Comment by wadudmiah** [comment]
Hi Stefano,

I had a brief look at it and the tool works fine with the NAG compiler. However, when I tell it to create the Makefile:

`FoBiS.py build -compiler nag -m Makefile`

and then type `make`, it does not add the compilation flag `-Imod/`

`nagfor -c -mdir mod -I./nested-1/nested-2  cumbersome.f90 -o obj/cumbersome.o`

The compiler then complains that it cannot find `nested_1` module:

`Fatal Error: cumbersome.f90, line 2: Cannot find module NESTED_1`

**Comment by szaghi** [comment]
Hi @wadudmiah 

thank you for the feedback, I'll check soon (tomorrow) why it fails, it should a "stupid" bug, I use very very few time the makefile generation feature...

stay tuned :-)

**Comment by wadudmiah** [comment]
Hi Stefano, I wanted to check that FoBiS can understand the F2008 module usage syntax:

`use, intrinsic :: iso_fortran_env`

The double-colon needs to be recognised by your tool. Older tools (F90) breakdown when the encounter this double-colon.

**Comment by szaghi** [comment]
Mmmm, I am not sure, sorry.

I have to check, but I am quite close to my summer-break... If I'll find the time tomorrow good, otherwise, please remember me this issue close to the end of August :-)

**Comment by wadudmiah** [comment]
Hi Stefano,

That's a very quick reply - not a very Italian response! manana, manana! haha!

**Comment by szaghi** [comment]
@wadudmiah I am closing this issue, feel free to re-open it or a new one if it is necessary
