### ISSUE TITLE
OpenMP

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FoBiS#48]
I'm trying to use FoBiS to compile some code that has OpenMP directives using gfortran.  If I add the ```-fopenmp``` flag to the cflags, it doesn't work.  I get errors on link like this:
```
Undefined symbols for architecture x86_64:
  "_GOMP_parallel", referenced from:
  ...
  "_omp_get_num_threads", referenced from:
  ...
  "_omp_get_thread_num", referenced from:
  ...
ld: symbol(s) not found for architecture x86_64
```
If I call gfortran manually with the ```-fopenmp``` flag, it works fine.  Any ideas?

**Comment by szaghi** [comment]
No, it is very strange. It seems that somthing is missed during the linking phase. Do you have tried adding `-fopenmp` also to the `-lfags`? When you say that *manually works* do you mean that you added `-fopenmp` during the final building of the executable (that includes the linking phase)? 

Anyhow, I can add a `-openmp` option to FoBiS (like the `-mpi` one) in order to ensure the correct conpilation... see you soon

**Comment by jacobwilliams** [comment]
When I say manually, I just mean typing: ```gfortran blah.f90 -o blah -fopenmp```.

Yes, an ```-openmp``` flag like the ```-mpi``` one would be a good idea, since I think the exact flags are different for the different compilers.

**Comment by szaghi** [comment]
In the new version there is `-openmp` option as you request. Anyhow, there was no related bug on the older version: the `-fopenmp` switch must be included into both compiling and linking flags. In your `manual` usage you are condensing the compiling and linking phase into one step, thus it works because the `-fopenmp` option is passed to both cflags and lflags: now you can do this with
```bash
FoBiS.py build -openmp ...
```
that is equivalent (also for older versions) to
```bash
FoBiS.py build -cflags " -c -openmp ..." -lflags " -openmp ..." ...
```
Of course, the pre-defined FoBiS.py switch `-openmp` works for only the supported compilers, i.e. the NAG compiler you are supporting is not supported by FoBiS.py (you must use the verbose invocation specifying the -cflags and -lflags).

I am closing this issue, but you can reopen it if the bug persists.

See you soon.
