### ISSUE TITLE
Some command switch to predefine output exe name?

### ISSUE THREAD

**Issue by zmiimz** [szaghi/FoBiS#51]
Currently the name of executable is defined by the name of the file with "program/end program"? Can it be predefined manually using some option switch?

**Comment by szaghi** [comment]
Sure, this name can be customized. Presently, the following rules are used:

+ if no target is specified (`-t`/`--target` switch), i.e. all programs found are built, the output name(s) are made by means of the `basename` of the programs sources, e.g. if the programs found are `src/foo.f90` and `src/bar.f90` the output name are `foo` and `bar`;
+ if target is specified, thus only the target is built, the output name is made by the following rules:
    + if no output is specified (`-o`/`--output` switch) the output name follows the source `basename` rule as above;
    + if output is specified it is used as it;
+ the output name of libraries follow the same rules of programs except that if no output is specified the suffix `.so` or `.a` is automatically added.

Consequently, the `program/end program` name is not currently used, rather it is used the basename of sources. If you want specify other name you must use the `-o`/`--output` switch. It is worth noting that this switch can also be defined into a fobos file.

One limit is that currently only one target can be specified. However, if you want to define many targets it should be simple to extend FoBiS to accept a list instead of only one values.

See you soon.

**Comment by zmiimz** [comment]
Good explanation. thnx

**Comment by tuncaen** [comment]
> 
> 
> Sure, this name can be customized. Presently, the following rules are used:
> 
>     * if no target is specified (`-t`/`--target` switch), i.e. all programs found are built, the output name(s) are made by means of the `basename` of the programs sources, e.g. if the programs found are `src/foo.f90` and `src/bar.f90` the output name are `foo` and `bar`;
> 
>     * if target is specified, thus only the target is built, the output name is made by the following rules:
>       
>       * if no output is specified (`-o`/`--output` switch) the output name follows the source `basename` rule as above;
>       * if output is specified it is used as it;
> 
>     * the output name of libraries follow the same rules of programs except that if no output is specified the suffix `.so` or `.a` is automatically added.
> 
> 
> Consequently, the `program/end program` name is not currently used, rather it is used the basename of sources. If you want specify other name you must use the `-o`/`--output` switch. It is worth noting that this switch can also be defined into a fobos file.
> 
> One limit is that currently only one target can be specified. However, if you want to define many targets it should be simple to extend FoBiS to accept a list instead of only one values.
> 
> See you soon.

Very clear explanation; however, I couldn't getting what I expected, though I am using as you explained to create `makefile` by using `fobos`, i.e.;

```
...
target       = src/main.f90
output     = UIHES.exe
...

```
the output file is as in the following,

```
...
$(DEXE)0-MAIN: $(MKDIRS) $(DOBJ)0-main.o
	@rm -f $(filter-out $(DOBJ)0-main.o,$(EXESOBJ))
	@echo $(LITEXT)
	@$(FC) $(OPTSL) $(DOBJ)*.o $(LIBS) -o $@
EXES := $(EXES) 0-MAIN
...
```

Am I missing something?
