### ISSUE TITLE
License in source code

### ISSUE THREAD

**Issue by sanguinariojoe** [szaghi/FoBiS#54]
It is safer to get a license note in every non-public-domain source code file. see:

http://www.gnu.org/licenses/gpl-howto.html

Regards!
Pepe

**Comment by szaghi** [comment]
Great Pepe!

**Comment by szaghi** [comment]
I have read the reference suggested, but I does not clearly understand how to fix the mising copyrigths into the sources.

I see to possible ways:
+ add a short note refering to the complete license file;
+ add the complete license.

While the short note can be added to each source file without too much cluttering, the second approach is not viable for me because the sources become unreadable.

Do you suggest to add some sort of short reference to the license file, or do you are suggesting to add the complete license?

Thank you Pepe, see you later (or soon it is already 6am...)

**Comment by sanguinariojoe** [comment]
The short reference is enough, of course

**Comment by szaghi** [comment]
Done
