### ISSUE TITLE
os.path.join instead of os.sep?

### ISSUE THREAD

**Issue by sanguinariojoe** [szaghi/FoBiS#57]
In _sanitize_dirs() (Builder.py:145), is it not more convenient using os.path.join() instead of manually concatenating os.sep separators?

**Comment by szaghi** [comment]
Sure, you are rigth! 

Thank you Pepe

**Comment by szaghi** [comment]
Done, but not everywhere.

The abuse of `os.sep` was *pervasive* and now is reduced but not completely purged. For some cases I have preferred to explicitly add the separator add the end of some *normalized* paths because I have some paths concatenation done without `os.path.join`... Before purging out completely `os.sep` I have to find all paths concatenation... this will done during the next code refactoring.
