### ISSUE TITLE
Release folder

### ISSUE THREAD

**Issue by Tobychev** [szaghi/FoBiS#78]
The release folder is very messy, and its hard to tell what is the latest release. 

I don't really understand why it seems like there are copies of the entire project there, it would be more appropriate to just tag a specific revision.

**Comment by szaghi** [comment]
:+1: 

It is due to my laziness... sorry. They are generated by my build.py pybuilder script that I love for testing the code locally (also generate the valid *eggs* for PyPi). I once committed the error to version also the pybuilder outputs... a I continue to do the same order. 

The next release will be sanitized!

Thank you Tomas to point it out.

**Comment by Tobychev** [comment]
Ok, thanks :)

**Comment by szaghi** [comment]
Directory sanitized.
